name: Build and Push GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: docker build -t rubika-uploader .

      - name: Tag Image
        run: |
          docker tag rubika-uploader ghcr.io/${{ github.repository_owner }}/rubika-uploader:latest

      - name: Push Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/rubika-uploader:latest